version: '3' 
services:
  app:
    build: ./app
    volumes:
     - ./app:/code
    restart: unless-stopped
  nginx:
    build: ./nginx 
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
     - app

